### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by zpp1996** [polatory/polatory#106]
Do you have a data set?What are the format requirements for the data set?

**Comment by mizuno-gsinet** [comment]
@namihisa-gsinet Could you elaborate on this?

**Comment by namihisa-gsinet** [comment]
A comma separated CSV format dataset is required to make kriging predictions using Polatory.
The CSV file consists of 4 columns: X coordinate, Y coordinate, Z coordinate, and physical quantity.

Example
```
50,50,-5,100
40,60,-4,110
30,70,-6,120
60,40,-8,90
…,…,…,…
```
