### ISSUE TITLE
CMake build error

### ISSUE THREAD

**Issue by iuming** [polatory/polatory#107]
Hello, I installed polatory on a Windows system. After completing `.\run init-vcpkg`, when running cmake, the following error occurred. What should I do to solve this error?
```
F:\RadL\Radiation_Field_Reconstruction\code\polatory>.\run cmake
The filename, directory name, or volume label syntax is incorrect.


    Directory: F:\RadL\Radiation_Field_Reconstruction\code\polatory


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        8/21/2020   7:40 PM                build
CMake Error at CMakeLists.txt:84 (message):
  Not supported system.


-- Configuring incomplete, errors occurred!
See also "F:/RadL/Radiation_Field_Reconstruction/code/polatory/build/CMakeFiles/CMakeOutput.log".
```

**Comment by namihisa-gsinet** [comment]
GNU is not a supported compiler at Polatory.

Could you try again in an environment without MinGW?

**Comment by iuming** [comment]
> Error occurs because GNU is not a supported compiler at Polatory.
> 
> Could you try again in an environment without MinGW?

Thank you very much, I used the linux system to reinstall, it has been successfully installed.
