### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by iuming** [polatory/polatory#108]
Is there any documentation for this open source code? Or can you write simple usage into the readme (a small suggestion)?

**Comment by namihisa-gsinet** [comment]
The documentation of Polatory is at the URL below.

https://polatory.readthedocs.io/en/latest/index.html

I'm sorry, but at present, only the explanation of RBF is described.

**Comment by iuming** [comment]
I saw this message in the replies to other Issuss:
```
Use kriging_variogram to create empirical variogram of your data.
Use kriging_fit to estimate model variogram parameters from the empirical variogram.
Use kriging_predict to run prediction and generate isosurfaces (contour surfaces in 3-D space).
```
Can you introduce more simple uses like this?

**Comment by namihisa-gsinet** [comment]
You can show help of the application by executing the application with no arguments.

For example, to show the help of `kriging_variogram`, execute the following command.
The options and the descriptions are shown.

```
>cd build\examples\kriging_variogram
>kriging_variogram
```

**Comment by iuming** [comment]
I'm sorry, please forgive my C++ is not very good.
If I measure these scattered points(3D), how do I perform kriging interpolation?
```
1.2 2.1 3.1 16.82
4.2 1.4 2.8 20.64
3.1 3.6 2.4 31.78
2.5 1.8 1.6 10.98
2.7 1.2 2.8 21.32
3.5 1.7 2.3 11.93
```
If you interpolate through this program, can you get the value of point A(1.5 2.2 2.7)? Which commands should be executed?

**Comment by namihisa-gsinet** [comment]
In Polatory, the results of kriging interpolation are OBJ format mesh files that express each isosurface.
So you can not get the value of a specific point itself.

**Comment by mizuno-gsinet** [comment]
@namihisa-gsinet

>So you can not get the value of a specific point itself.

If that were the case, it would not be possible to generate isosurfaces.

**Comment by namihisa-gsinet** [comment]
> So you can not get the value of a specific point itself.

I want  to say the following.

Command execution results of `kriging_predict` are OBJ format mesh files.
Prediction value of a specific point is not returned, by executing `kriging_predict` command.

**Comment by mizuno-gsinet** [comment]
@iuming Did that answer your question?

**Comment by iuming** [comment]
Thank you very much, if possible, can you add a function to express the special points?  If the calculation of special points is before the step of generating isosurfaces.

**Comment by mizuno-gsinet** [comment]
@namihisa-gsinet Can you prepare an example program for that?

**Comment by iuming** [comment]
> I'm sorry, please forgive my C++ is not very good.
> If I measure these scattered points(3D), how do I perform kriging interpolation?
> ```
> 1.2 2.1 3.1 16.82
> 4.2 1.4 2.8 20.64
> 3.1 3.6 2.4 31.78
> 2.5 1.8 1.6 10.98
> 2.7 1.2 2.8 21.32
> 3.5 1.7 2.3 11.93
> ```
> If you interpolate through this program, can you get the value of point A(1.5 2.2 2.7)? Which commands should be executed?

For example, can some simple data like this?

**Comment by namihisa-gsinet** [comment]
I added an example program  to the branch `issue-108`  that outputs the prediction values of the specified points.

https://github.com/polatory/polatory/pull/110

This program, `kriging_predict_special_points`, outputs the prediction values as a text file.

Usage,
```
Usage: kriging_predict_special_points [OPTION]...
Options:
  --in FILE                   Input file in CSV format:
                                X,Y,Z,VAL
  --points FILE               Prediction points file in CSV format:
                                X,Y,Z
  --min-dist VAL (=1e-10)     Minimum separation distance of input points
  --rbf ...                   RBF/covariance function, one of:
                              Positive definite
                                exp VAR SCALE  (cov_exponential)
                                sp3 VAR SCALE  (cov_spheroidal3)
                                sp5 VAR SCALE  (cov_spheroidal5)
                                sp7 VAR SCALE  (cov_spheroidal7)
                                sp9 VAR SCALE  (cov_spheroidal9)
                              Conditionally positive definite of order 1
                                bh3 VAR        (biharmonic3d)
                              Conditionally positive definite of order 2
                                bh2 VAR        (biharmonic2d)
  --aniso A11 A12 A13 A21 A22 A23 A31 A32 A33 (=1. 0. 0. 0. 1. 0. 0. 0. 1.)
                              Elements of the anisotropy matrix
  --nugget VAL (=0.)          Nugget of the model
  --dim 1|2|3 (=3)            Dimension of the drift polynomial
  --deg -1|0|1|2 (=0)         Degree of the drift polynomial
  --tol VAL                   Absolute tolerance of the fitting
  --out FILE                  Prediction values output file:
```

**Comment by iuming** [comment]
Thank you very much, I think I will probably use it easily.
