### ISSUE TITLE
Unity Compatibility

### ISSUE THREAD

**Issue by nakedtiger666** [polatory/polatory#111]
I am wondering if it is possible to add a C interface for the methods and build it as a .dll that I can use as a native plug-in from Unity, like it says here:
https://docs.unity3d.com/Manual/NativePlugins.html
https://www.mono-project.com/docs/advanced/pinvoke/

I have done it in the past already with [this great C++ voronoi library](https://github.com/fabanc/SharpBoostVoronoi) like this:
```
extern "C"
{
	DLLExport int run(_site* sites, int sitesN, _segment* segments, int segmentsN,
		_vertex* verts, int* vertsSize,
		_edge* edges, int* edgesSize,
		_cell* cells, int* cellsSize,
		int* edge_identifiers, int e_dim, int e_step,
		int* vertex_identifiers, int v_dim, int v_step)
	{
                 // ... inits all classes, does all calculations and fills the result arrays
        }
}
```

Which simply passes all preallocated data for the calculation from managed C# code, lets the C++ do its job and then returns the results back to C#. I need this to build a surface from a few 3D points in runtime from Unity.

**Comment by namihisa-gsinet** [comment]
It is possible to add methods to Polatory and build it as a .dll.

An example program that creates the isosurfaces of the predict results is following link.
You can use it as a reference when implementing the methods.

https://github.com/polatory/polatory/tree/master/examples/kriging_predict

The usage is following.

```
Usage: kriging_predict [OPTION]...
Options:
  --in FILE                   Input file in CSV format:
                                X,Y,Z,VAL
  --min-dist VAL (=1e-10)     Minimum separation distance of input points
  --rbf ...                   RBF/covariance function, one of:
                              Positive definite
                                exp VAR SCALE  (cov_exponential)
                                sp3 VAR SCALE  (cov_spheroidal3)
                                sp5 VAR SCALE  (cov_spheroidal5)
                                sp7 VAR SCALE  (cov_spheroidal7)
                                sp9 VAR SCALE  (cov_spheroidal9)
                              Conditionally positive definite of order 1
                                bh3 VAR        (biharmonic3d)
                              Conditionally positive definite of order 2
                                bh2 VAR        (biharmonic2d)
  --aniso A11 A12 A13 A21 A22 A23 A31 A32 A33 (=1. 0. 0. 0. 1. 0. 0. 0. 1.)
                              Elements of the anisotropy matrix
  --nugget VAL (=0.)          Nugget of the model
  --dim 1|2|3 (=3)            Dimension of the drift polynomial
  --deg -1|0|1|2 (=0)         Degree of the drift polynomial
  --tol VAL                   Absolute tolerance of the fitting
  --mesh-bbox XMIN YMIN ZMIN XMAX YMAX ZMAX
                              Output mesh bounding box
  --mesh-res VAL              Output mesh resolution
  --mesh-isoval VAL...        Output mesh isovalues
  --mesh-out FILE...          Output mesh files in OBJ format
the option '--in' is required but missing
```

**Comment by nakedtiger666** [comment]
How to actually build a .dll out of kriging_predict instead of the default .exe?

**Comment by nakedtiger666** [comment]
It is not clear what is the acceptable range of the input values... Could you please link an example of calling the .exe or point a place where these values are being checked after the parsing? 

I am trying these args and the error code is 'bad lexical cast: source type value could not be interpreted as target"

`"--in C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmp409666f6.tmp --rbf exp 1. 1. --tol 1. --mesh-bbox -100. -100. -100. 100. 100. 100. --mesh-res 100. --mesh-isoval 100. --mesh-out C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmp1b95b4f0.tmp"`

**Comment by mizuno-gsinet** [comment]
@nakedtiger666 Could you describe the task you are trying to do? Is it surface modeling, surface reconstruction, interpolation, or something else?

**Comment by namihisa-gsinet** [comment]
> It is not clear what is the acceptable range of the input values... Could you please link an example of calling the .exe or point a place where these values are being checked after the parsing?

There is no place to check input values ​​in kriging_predict.exe.
So execute kriging_predict.exe after checking that all the input values ​​are not the same.

``` cs
            double[] values = ReadInputDataFromCsv();
            
            if (values.Max().Equals(values.Min()))
            {
            	Console.Write("Cannot interpolate because all input data has the same value.");
                return;
            }
            
            // Execute kriging_predict
            
```

**Comment by mizuno-gsinet** [comment]
@namihisa-gsinet I think the OP is not trying to do kriging.

**Comment by nakedtiger666** [comment]
> @nakedtiger666 Could you describe the task you are trying to do? Is it surface modeling, surface reconstruction, interpolation, or something else?

I want to build 3d terrain (low poly mountains) out of the 3d interactive tree graph. Lets say it will look very similar to [this](https://uploads-ssl.webflow.com/5d64ad209093d7b315c3591a/5e969612878648b8c23a88a7_unity-game-asset-low-poly-modular-terrain-pack-demo_1.jpg)

Each node of the graph can be moved around in 3d space (ofc I will make sure the nodes of the graph are not too close and the edges are not intersecting from the top view). To build mountains out of the graph I plan to first calculate the [line segment voronoi diagram](https://i.stack.imgur.com/1NDjV.png) out of the edges and free nodes of the graph. I will then remove edges of voronoi cells where the edges of tree graph actually are connected to form sort of rough outline of the independent branches, [smth like this](https://ibb.co/YDTJGFn) (please note that I've added 2 edges to the previous voronoi diagram to showcase the idea of blending of cells) Then what I expect from kriging is to extrapolate (I might use wrong term) the continuous 3d surface by passing it points that align with the edges of voronoi blended cells (the Z value of those points will be always be 0, because they will be the one who I expect to ground the surface between mountains range) and also by passing points that align with actual graph - all its nodes as they are with all their height and multiple points across the edges that connect these nodes which of course will be tilted due to the fact that nodes of each graph edge can have different height. Like [this](https://ibb.co/6t8rJ71) purple points belong to the voronoi diagram and orange points belong to the graph.

At the end I expect to achieve smth like [this](https://ibb.co/LY4nHCS), perhaps the smooth and gradient height map will do, which I can then use to reconstruct the 3d mesh in Unity and all of this in real time. Hope that makes sense to you now..



> There is no place to check input values ​​in kriging_predict.exe.

Sorry, my question was not clear enough, I meant different. I wanted to ask what is the range of the values of mesh-res, mesh-isoval, tol VAL, VAR and SCALE of rfb functions and so on. I don't quite understand how they should look like, super small, big or they all should be small or big at the same time, you get the idea haha

**Comment by namihisa-gsinet** [comment]
Is it OK that what you want to achieve with Polatory is to build a 3D surface from points that align with the edges of voronoi blended cells and points that align with actual graph?


Since `kriging_predict` is a program that builds isosurfaces, it cannot build a 3D terrain consisting of points of different elevations.
Polatory also has a example program called `terrain_surface` to build a 3D surface.
The input data is a CSV file consisting of 3 columns of X,Y,Z coordinates.

https://github.com/polatory/polatory/tree/master/examples/terrain_surface

Usage:
```
Usage: terrain_surface [OPTION]...
Options:
  --in FILE                   Input file in CSV format:
                                X,Y,Z
  --min-dist VAL (=1e-10)     Minimum separation distance of input points
  --rbf ...                   RBF/covariance function, one of:
                              Positive definite
                                exp VAR SCALE  (cov_exponential)
                                sp3 VAR SCALE  (cov_spheroidal3)
                                sp5 VAR SCALE  (cov_spheroidal5)
                                sp7 VAR SCALE  (cov_spheroidal7)
                                sp9 VAR SCALE  (cov_spheroidal9)
                              Conditionally positive definite of order 1
                                bh3 VAR        (biharmonic3d)
                              Conditionally positive definite of order 2
                                bh2 VAR        (biharmonic2d)
  --smooth VAL (=0.)          Amount of spline smoothing
  --deg -1|0|1|2 (=0)         Degree of the polynomial
  --tol VAL                   Absolute tolerance of the fitting
  --mesh-bbox XMIN YMIN ZMIN XMAX YMAX ZMAX
                              Output mesh bounding box
  --mesh-res VAL              Output mesh resolution
  --mesh-out FILE             Output mesh file in OBJ format
```

**Comment by nakedtiger666** [comment]
terrain_surface is exactly what I was looking for, but calling the .exe in runtime and waiting until it writes down the .obj to the disk and then reimporting it back into the Unity takes some time. Is it possible to return a simple heightmap after the isosurface generation instead of the .obj, so I can recreate my own mesh in Unity based on it? I want the whole process to take no more than 20ms on the average PC.

**Comment by namihisa-gsinet** [comment]
Polatory has a method that returns the results of interpolation for specific points.
So it is possible by modifying the `terrain_surface` to return the interpolated values for the grid points (X, Y).
After that, I think that it can be realized by outputting the heightmap from the grid-like return values.

**Comment by nakedtiger666** [comment]
That is a good way to go. 

> It is possible to add methods to Polatory and build it as a .dll.
You have mentioned this, but could you also explain how it can be done? I want to have a .dll that my Unity project could use on both win and mac. If I understand everything correctly - I need to build it as a .dll in order to be able to run on mac and in order to have more faster calculations without a need to write down input csv file and start the .exe process. Right now the whole process takes me about 5-8 secs, I want it to be 20ms.

So far I have a great success using Polatory, I'm amazed by the quality of the solution. Good job guys, thanks.

**Comment by namihisa-gsinet** [comment]
> That is a good way to go. What is a name of the method that returns interpolated (X,Y) grid?

The following method.
https://github.com/polatory/polatory/blob/master/include/polatory/interpolant.hpp#L39

**Comment by nakedtiger666** [comment]
Beg your pardon, but it seems to me there is no way of building the whole Polatory code into a single .dll, is it? I want this to access terrain_surface functionality not only on Win, but on WebGL and Mac.

**Comment by namihisa-gsinet** [comment]
Instead of building the whole Polatory into a single dll, you can build `terrain_surface.dll` by modifying `add_executable` in `CMakeLists.txt` to `add_library`.
It is possible to access the function of  `terrain_surface` from outside the `terrain_surface.dll` by using a method with `extern "C" __declspec (dllexport) `instead of the main function.
