### ISSUE TITLE
Questions about operating parameter errors

### ISSUE THREAD

**Issue by iuming** [polatory/polatory#113]
Hello, I'm very sorry, I have some doubts when I run polatory. In the previously mentioned Kriging discrete point prediction, when I used this program, when I input `./kriging_predict_special_points --in inputdata.csv --out output.csv --point pointsdata.csv --rbf exp --tol 0.1 --dim 2`, an error message `params.size() must be 2.` appeared. Could you tell me where I entered incorrectly?
The data in the input.csv file is:
```
0.0,0.0,0.2
0.0,1.0,0.0
1.0,0.0,0.0
1.0,1.0,-0.2
0.4,0.4,-1.0
0.6,0.6,1.0
```
The data in the pointsdata.csv file is:
```
0.3,0.7
```

**Comment by iuming** [comment]
#110

**Comment by namihisa-gsinet** [comment]
The option `--rbf` in `kriging_predict_special_points` must specify the partial sill and the scale after the function abbreviation.

To specify 1.0 for both, write as follows.

```
--rbf exp 1.0 1.0
```

Change the option to specify the file name of the predeiction points to `--points`.
