### ISSUE TITLE
Kriging of a Spherical Surface 

### ISSUE THREAD

**Issue by nakedtiger666** [polatory/polatory#115]
Hi. Is it possible to krige the surface of a sphere? Imagine we input a spherical height map, and then we want to test the sphere grid points to recreate an interpolated topology. Can an enclosed surface be kriged at all?

**Comment by namihisa-gsinet** [comment]
If you have point data with normals, executing the example program `normals_sdf` will generate point data with SDFs (Signed Distance Function).

https://github.com/polatory/polatory/tree/master/examples/normals_sdf

The usage is following.

```
Usage: normals_sdf [OPTION]...
Options:
  --in FILE              Input file in CSV format:
                           X,Y,Z,NX,NY,NZ
  --min-offset VAL (=0.) Minimum offset distance of off-surface points
  --offset VAL           Default offset distance of off-surface points, the
                         average distance between adjacent points is a
                         reasonable choice
  --mult 1.-3. (=2.)     Multiplication factor of sdf data
  --out FILE             Output file in CSV format:
                           X,Y,Z,VAL
```

Then you can create a closed surface by creating an isosurface of 0.0 executing `kriging_predict`.

**Comment by nakedtiger666** [comment]
is that really so straightforward? looks amazing, you guys have a powerful solution one might say.

**Comment by nakedtiger666** [comment]
> creating an isosurface of 0.0
0.0 is one of the parameters of the isosurface constructor?

**Comment by namihisa-gsinet** [comment]
>  0.0 is one of the parameters of the isosurface constructor?

Set `kriging_predict` parameter `--mesh-isoval`  to 0.0 to generate a 0.0 valued isosurface.
This isosurface is the closed surface you want.
