### ISSUE TITLE
Polygon Boundaries

### ISSUE THREAD

**Issue by ghost** [polatory/polatory#118]
Is it possible to add a polygon boundaries for the kriging area? So the outline of the boundaries would ground the interpolated surface to zero. I am using 10k points to 'imitate' the boundaries by placing them along the boundaries outline very closely to each other, I am wondering if there is more convenient and faster way to outline. Thanks.

**Comment by namihisa-gsinet** [comment]
The predicted area by `terrain_surface` is only a cuboid box.

**Comment by nakedtiger666** [comment]
It looks to me that only deep modification of the interpolation algo itself for this specific case could speed up the calculations or make fast dynamic area constrain work. Correct me if I am missing something. Thank you for the reply :)
