### ISSUE TITLE
[RUN ERROR]Rank cannot be larger than size

### ISSUE THREAD

**Issue by iuming** [polatory/polatory#119]
Hello, when I am running Kriging special point interpolation, when I input the following command, the terminal reports this error. What is the cause? What action do I need to change to solve this problem? Hope to get help, thank you very much!
```
./kriging_predict_special_points --in data.csv --out output.csv --points points.csv --rbf exp 1.0 1.0 --tol 0.1
rank cannot be larger than size
```

**Comment by namihisa-gsinet** [comment]
Could you tell me `data.csv` executed the above command?

**Comment by iuming** [comment]
@namihisa-gsinet this is `data.csv` as follow:
```
-125,-125,-225,0.175218
-125,-25,-225,0.206606
-125,75,225,0.214508
-75,-75,25,1.24852
-75,-25,-25,2.04387
-25,-175,25,0.383692
-25,25,-225,0.246601
-25,-25,25,5.92098
-25,125,175,0.299306
25,25,-25,5.8376
75,-175,-225,0.175232
75,-75,-25,1.21627
75,-25,225,0.223151
125,175,-75,0.264945
125,175,225,0.162468
```

**Comment by namihisa-gsinet** [comment]
This error is caused by a third party library used by Polatory.
How about use another model?

**Comment by unageek** [comment]
The range parameter (the second parameter of `--rbf exp 1.0 1.0`) is too small compared to the spacing of the input data. Try a larger value.
