### ISSUE TITLE
Info about the ISO surface algorithm used

### ISSUE THREAD

**Issue by kxdniu** [polatory/polatory#120]
Can you please tell me what the iso surface algorithm is based on? Any relevant information is appreciated.

**Comment by namihisa-gsinet** [comment]
Divide the entire model into lattices and generate a surface for each lattice.
See below for the algorithm to generate surfaces.

https://github.com/polatory/polatory/blob/master/include/polatory/isosurface/rmt_surface.hpp#L251

**Comment by unageek** [comment]
Regularised marching tetrahedra (RMT) [10.1016/S0097-8493(99)00076-X](https://doi.org/10.1016/S0097-8493(99)00076-X) is implemented.
