### ISSUE TITLE
A problem arises in the reconstruction of three dimensional implicit surfaces

### ISSUE THREAD

**Issue by RainSureZhao** [polatory/polatory#135]
When I used polatory for 3D surface reconstruction, the results of my reconstruction did not meet expectations.
#### 1. Use **terrain_normal** to generate normal vectors for each point in the original point cloud.
The command line parameters are as follows:
terrain_normals.exe --in=bunny.csv --out=bunny_normals.csv
##### This can be described in Visual Studio 2022 as follows:
![image](https://user-images.githubusercontent.com/73586413/219078865-da4bd5a0-2918-4600-82c7-64cf9bf81fb0.png)

#### 2. **normals_sdf** is used to construct the signed distance function of the normal vector generated in the first step.
The command line parameters are as follows:
normals_sdf.exe --in=bunny_normals.csv --offset=0.00001 --out=bunny_sdf.csv
##### This can be described in Visual Studio 2022 as follows:
![image](https://user-images.githubusercontent.com/73586413/219079796-b60cb864-e045-47a2-9269-d47889d14347.png)

#### 3. Use **kriging_perdict** to generate implicit surfaces and surface evaluations.
The command line parameters are as follows:

kriging_predict.exe --in=buny_sdf.csv --rbf=bh3 1 --nugget=0.0 --dim=3 --deg=0 --tol=0.001 --mesh-bbox= -0.1 -0.05 -0.2 0.06 0.2 0.2 --mesh-res=0.001 --mesh-isoval=0.0 --mesh-out=bunny.obj
#### This can be described in Visual Studio 2022 as follows:
![image](https://user-images.githubusercontent.com/73586413/219081793-2554c99f-8b37-4447-aa99-44662bdfb57e.png)

The original point cloud file, along with the intermediate generated file and the end result (bunny.obj) are in the uploaded attach files.
[bunny.csv](https://github.com/polatory/polatory/files/10744940/bunny.csv)
[bunny_normals.csv](https://github.com/polatory/polatory/files/10744941/bunny_normals.csv)
[bunny_sdf.csv](https://github.com/polatory/polatory/files/10744949/bunny_sdf.csv)

Github doesn't seem to allow uploading obj files, so I uploaded it to Google Cloud Drive and shared it. Here's the link:
https://drive.google.com/file/d/1GlpTr_Q18-QNzf9e573RGRcjbWCaNBLA/view?usp=sharing

**Comment by RainSureZhao** [comment]
> Hi!
> 
> `terrain_normals` does not properly estimate normals of closed surfaces (as its name suggests, it's for 2.5D data). Could you try using CloudCompare for normal estimation?

Thank you very much. I will try to use CloudCompare for normal estimation.

**Comment by RainSureZhao** [comment]
> Hi!
> 
> `terrain_normals` does not properly estimate normals of closed surfaces (as its name suggests, it's for 2.5D data). Could you try using CloudCompare for normal estimation?
> 
> [Here](https://github.com/polatory/polatory/commit/4d49023d92c10046eff043e1978eb49ccc9b5eb6#commitcomment-100702886) is a link to the previous discussion for reference.

Hello, after I calculated the normal vector using CloudCompare and reconstructed the surface again, the result is correct. But I'd like to know if polatory can support normal vector estimation of closed surfaces, and if not why? Will I be able to participate in the project? I want to do some work on estimating normal vectors for closed surfaces.
![image](https://user-images.githubusercontent.com/73586413/219258172-93e49c4f-2af0-48c1-be0a-e439d32d0341.png)

**Comment by unageek** [comment]
Hi, I'm glad to hear that!

Consistently orienting normals for a closed surface could be difficult, but here is the outline of a candidate algorithm. Maybe you can implement it to normal_estimator.hpp.

```
Input: a point cloud, an arbitrary point outside the surface (p_outside), parameters for the nearest neighbor search algorithm
Output: the point cloud with normals
Algorithm:
1. Estimate per-point normal (not consistently oriented at this point)
2. For each connected component of the point cloud (in terms of the nearest neighbor search):
3.     Find the nearest point (p) in the component to the p_outside
4.     Orient the normal of p so that it aligns with the vector p_outside - p.
5.     Propagate the orientation of normals
```

**Comment by RainSureZhao** [comment]
> Hi, I'm glad to hear that!
> 
> Consistently orienting normals for a closed surface could be difficult, but here is the outline of a candidate algorithm. Maybe you can implement it to normal_estimator.hpp.
> 
> ```
> Input: a point cloud, an arbitrary point outside the surface (p_outside), parameters for the nearest neighbor search algorithm
> Output: the point cloud with normals
> Algorithm:
> 1. Estimate per-point normal (not consistently oriented at this point)
> 2. For each connected component of the point cloud (in terms of the nearest neighbor search):
> 3.     Find the closest point (p) in the component to the p_outside
> 4.     Orient the normal of p so that it aligns with the vector p_outside - p.
> 5.     Propagate the orientation of normals using the nearest neighbor search
> ```

Thank you very much. I will try my best to finish this task.

**Comment by RainSureZhao** [comment]
Hello, I have tried to implement the algorithm of estimating the normal vector of each point of the closed surface in normal_estimator.hpp according to the algorithm steps you gave, and have carried out many experiments, but the results are not satisfactory. Could you check my code and help me see if there is any problem?

Here is the code link:
https://paste.ubuntu.com/p/9KWpWxKhXs/

**Comment by unageek** [comment]
In this case, a connected component is a set of points such that any point is reachable from any other point by repeated kNN searches.

**Comment by RainSureZhao** [comment]
> connected component

Ok, I see. I was wrong about the connected component.
