### ISSUE TITLE
CMake error during building on Windows

### ISSUE THREAD

**Issue by harmony96** [polatory/polatory#167]
I installed Visual studio 2022 (community edition).
Under workloads,  Desktop&Mobile with "desktop development with c++" was selected.
Also, "Git for Windows" was installed.

After rebooting the computer, tried to build.
I got the following error message during running "./run configure".

![image](https://github.com/polatory/polatory/assets/128596597/6926feb1-64e1-43ff-b76e-ce93e636a874)

**Comment by unageek** [comment]
Hi! Please try deleting the `build` directory and running `./run configure` again.

To build Polatory from the `main` branch, you also need Clang 17. Please download `LLVM-17.0.5-win64.exe` [here](https://github.com/llvm/llvm-project/releases/tag/llvmorg-17.0.5) and install it. Make sure you have added `C:\Program Files\LLVM\bin` to PATH.

**Comment by harmony96** [comment]
Thank you. After installing CClang 17, everything is perfect now.

**Comment by DaveOnDET** [comment]
I got the following error message during running "./run configure". 
with vs2022 ,and  LLVM-17.0.5-win64.exe installed.

<img width="973" height="197" alt="Image" src="https://github.com/user-attachments/assets/d3bf77e7-3752-4121-88ff-1f8ea8255c0a" />
