### ISSUE TITLE
interpolation of 3D field with scatter points

### ISSUE THREAD

**Issue by manuel76413** [polatory/polatory#168]
how to use polatory library to implement 3D field interpolation based on several scatter points?
can somebody give a sample？

**Comment by manuel76413** [comment]
> Hi! If you want to generate isosurfaces, please take a look at https://github.com/polatory/polatory/blob/main/examples/kriging_predict/main.cpp, or if you want to evaluate the interpolant at specific points, try [`interpolant.evaluate()`](https://github.com/polatory/polatory/blob/2efc7ff57dd223d98686a4687bb1e7266d54c311/include/polatory/interpolant.hpp#L43).

No, I don't need isosurfaces, I need multi-3D points' value.
the question is  I have several scatter 3D points, every point has a scalar value, now need to get dense points based on these existed points, I don't know how to solve by use polatory library

**Comment by unageek** [comment]
@manuel76413 Have you tried [`interpolant.evaluate()`](https://github.com/polatory/polatory/blob/2efc7ff57dd223d98686a4687bb1e7266d54c311/include/polatory/interpolant.hpp#L43)?
