### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by raypenper** [polatory/polatory#41]
when I cmake the code:
cmake .. -GNinja -DCMAKE_TOOLCHAIN_FILE=G:/Envir/vcpkg/scripts/buildsystems/vcpkg.cmake

it comes to an error:
![image](https://user-images.githubusercontent.com/41855946/50570927-cb36b280-0dd7-11e9-92b6-ecec1093e97e.png)

please tell me how to solve that?

**Comment by mizuno-gsinet** [comment]
@raypenper 

1. What is the version of Visual Studio 2017 installed? The latest version at this moment is 15.9.4. If you have an older one, please consider updating it.

2. Please make sure you have installed dependent libraries through vcpkg with `--triplet x64-windows` option.

**Comment by raypenper** [comment]
thank you but i have the latest version of VS2017 and i am sure that i have installed dependent libraries vcpkg.It still doesn't work.
![image](https://user-images.githubusercontent.com/41855946/50733020-49bc9700-11c0-11e9-873d-155dfa6e41e0.png)

**Comment by mizuno-gsinet** [comment]
@raypenper Thank you for the confirmation. Could you check your VS installation by running the following commands?

```cmd
where cmake
cmake --version
where ninja
ninja --version
```

This is the expected output:

![versions](https://user-images.githubusercontent.com/29035331/50866775-bcab5500-13ee-11e9-8681-20ca3d8caedc.png)

**Comment by mizuno-gsinet** [comment]
@raypenper CMake and Ninja are bundled in "Desktop development with C++" workload of VS2017. Could you confirm that the workload is installed? (Launch Visual Studio Installer, click **Modify** button and see if **Desktop development with C++** is checked)

**Comment by raypenper** [comment]
@mizuno-gsinet Thank you, but after i installed the nessesary items(Desktop development with C++ and Gits for Windows), the problem still remains.

![image](https://user-images.githubusercontent.com/41855946/50893371-9f50a800-143b-11e9-8582-441645830bb5.png)

**Comment by raypenper** [comment]
@mizuno-gsinet Oh,it took a long time to reinstall all the libraries,but, disappointingly, it still went wrong.

![image](https://user-images.githubusercontent.com/41855946/50946936-d922bc80-14d6-11e9-8803-f0eb68e1e1cb.png)

**Comment by raypenper** [comment]
@mizuno-gsinet yes,i delete all files in build dir and recmake command.the error now becomes "Not supported system"

![image](https://user-images.githubusercontent.com/41855946/50949383-ee044d80-14e0-11e9-800a-46d61e025635.png)

**Comment by mizuno-gsinet** [comment]
@raypenper Oh, I'm sorry but only MSVC is supported on Windows.

**Comment by raypenper** [comment]
@mizuno-gsinet Thank you, but is there any other way to solve the problem?how could the error be?

**Comment by mizuno-gsinet** [comment]
@raypenper Can you remove CC and CXX environment variables if they are set?

**Comment by raypenper** [comment]
@mizuno-gsinet Amazing. Thanks you. you are very helpful. i think we almost did it. Should i install mkl libraries into C:?
![image](https://user-images.githubusercontent.com/41855946/51018097-5a4e8200-15b1-11e9-8bf2-195faeae34a9.png)

**Comment by mizuno-gsinet** [comment]
@raypenper No, you can specify the MKL installation directory as:

```cmd
cmake .. -GNinja -DCMAKE_TOOLCHAIN_FILE=G:/Envir/vcpkg/scripts/buildsystems/vcpkg.cmake -DMKL_ROOT=G:/environment/intel/IntelSWTools/compilers_and_libraries/windows/mkl
```

**Comment by raypenper** [comment]
@mizuno-gsinet Thank you very much. i think the whole project have been build successfully. but i'm at a loss. How to run it? i did't find a way to debug(.sln). can i run it via VS2017?Sorry i am just too ignorant.

**Comment by raypenper** [comment]
@mizuno-gsinet Thank you. When i try to run any of the example program. it produced the similar error.
![image](https://user-images.githubusercontent.com/41855946/51153230-5751db00-18aa-11e9-821e-f8c226fd0c7a.png)

**Comment by mizuno-gsinet** [comment]
@raypenper Please add a breakpoint to the lines below to keep the console window open.

https://github.com/polatory/polatory/blob/370a2a4ac650b114169879d33aaf7d7044d16310/examples/kriging_cross_validation/main.cpp#L42

https://github.com/polatory/polatory/blob/370a2a4ac650b114169879d33aaf7d7044d16310/examples/kriging_cross_validation/main.cpp#L45

https://github.com/polatory/polatory/blob/370a2a4ac650b114169879d33aaf7d7044d16310/examples/kriging_cross_validation/parse_options.hpp#L59

![image](https://user-images.githubusercontent.com/29035331/51155859-69d51000-18bc-11e9-91fe-281fbb4b66db.png)

**Comment by raypenper** [comment]
@mizuno-gsinet yes. the console window shows the same result.

![image](https://user-images.githubusercontent.com/41855946/51176646-71b2a580-18f8-11e9-9042-ed3ead4ba4df.png)

**Comment by mizuno-gsinet** [comment]
@raypenper Good! Now if you add appropriate command line arguments, the program should run. Do you have any input data?

**Comment by raypenper** [comment]
@mizuno-gsinet yes,i have some input data.the data format should be x,y,z and value(4D),right? but i don't know how to use the program to process my data. if only the project were visualized.

**Comment by mizuno-gsinet** [comment]
@raypenper Ok, that is the typical kind of input data. Could you describe the problem you want to solve in detail?

**Comment by raypenper** [comment]
@mizuno-gsinet Sorry, the main obstacle is that i do not know how to use kriging to interpolate my data. i 
 think i should study through the code.

**Comment by mizuno-gsinet** [comment]
@raypenper If you are looking for a general-purpose kriging/spatial interpolation library, I suggest you take a look at these ones:

- R packages for kriging: [geoR](https://cran.r-project.org/web/packages/geoR/index.html) or [gstat](https://cran.r-project.org/web/packages/gstat/)
- [scipy.interpolate](https://docs.scipy.org/doc/scipy/reference/interpolate.html)

**Comment by raypenper** [comment]
@mizuno-gsinet Thank you. but i don't understand R language. can you teach me how to use my 3-D data to perform Kriging interpolation in polatory?

**Comment by mizuno-gsinet** [comment]
@raypenper OK, but first I need to know how much knowledge you have about kriging. Does the first paragraph of the [Wikipedia article](https://en.wikipedia.org/wiki/Kriging) make sense to you? If it doesn't, I strongly recommend reading a textbook about kriging. There are some tutorials for the geoR/gstat packages on the web.

**Comment by raypenper** [comment]
@mizuno-gsinet Yes. I understand the principle of kriging and i deduced the formulas of it. but i don't know how to use the program to process the data.

**Comment by mizuno-gsinet** [comment]
@raypenper I see. The basic usage is as follows:

1. Use [kriging_variogram](https://github.com/polatory/polatory/tree/master/examples/kriging_variogram) to create empirical variogram of your data.
2. Use [kriging_fit](https://github.com/polatory/polatory/tree/master/examples/kriging_fit) to estimate model variogram parameters from the empirical variogram.
3. Use [kriging_predict](https://github.com/polatory/polatory/tree/master/examples/kriging_predict) to run prediction and generate isosurfaces (contour surfaces in 3-D space).

At this moment, the model variogram is fixed to [cov_quasi_spherical9](https://github.com/polatory/polatory/blob/370a2a4ac650b114169879d33aaf7d7044d16310/include/polatory/rbf/cov_quasi_spherical9.hpp#L25-L27), which is similar to spherical variogram, and you need to edit the source code (main.cpp of each example program) to use another one.

As you can see, there are no manuals for these programs except the usage messages. Just try using them and should you have any questions, please feel free to ask me.

**Comment by mizuno-gsinet** [comment]
As the build error is resolved, this issue should be closed.

@raypenper Please open a new issue for further questions.

**Comment by raypenper** [comment]
@mizuno-gsinet OK, i will try using these models. Thank you very much.
