### ISSUE TITLE
Kriging interpolation method

### ISSUE THREAD

**Issue by raypenper** [polatory/polatory#43]
@mizuno-gsinet Hi, i am here again. I took your advise and tried debugged the kriging_variogram model. the command window just flashed and closed. Can you tell me where should i put my source data? and in every model i need to add breakpoints before "return 0" and "return 1", right？

![image](https://user-images.githubusercontent.com/41855946/53381983-9dbc4e80-39ad-11e9-9cd6-32210ee89ea9.png)

**Comment by mizuno-gsinet** [comment]
@raypenper Yes, Visual Studio does not keep the console window open for CMake projects.

**Comment by raypenper** [comment]
@mizuno-gsinet yes, and what is the path of source data for interpolation?

**Comment by mizuno-gsinet** [comment]
Please set command line arguments as explained in [this doc](https://docs.microsoft.com/en-us/cpp/ide/cmake-tools-for-visual-cpp?view=vs-2017#configure-cmake-debugging-sessions).

>To customize the debugger settings for any executable CMake target in your project, right-click on the specific CMakeLists.txt file and select Debug and Launch Settings. ...

In this case, you should right-click `CMakeLists.txt` under the `examples/kriging_variogram` directory. Then, set arguments as:

```
      "args": [
        "--in C:\\path\\to\\data.txt some more options ..."
      ]
```

Before debugging, please pull the [latest commit](https://github.com/polatory/polatory/commit/cca97e85afaabf19fc01ac6d470dc3137b3710d6) so that the breakpoints you set in main.cpp are always hit.

**Comment by raypenper** [comment]
@mizuno-gsinet Thank you, but the console window still flashed and closed. 

![image](https://user-images.githubusercontent.com/41855946/53407394-1693c880-39f7-11e9-99d3-f370f5b63b13.png)

![image](https://user-images.githubusercontent.com/41855946/53407509-522e9280-39f7-11e9-93e2-574a70dc1f8f.png)

![image](https://user-images.githubusercontent.com/41855946/53407548-65d9f900-39f7-11e9-8c32-425fcfe37498.png)

![image](https://user-images.githubusercontent.com/41855946/53407572-72f6e800-39f7-11e9-9f7e-77954b6b1f33.png)

**Comment by mizuno-gsinet** [comment]
@raypenper Could you confirm that

1. You have pulled the latest `master` branch (not of your fork!)

1. The configuration is set to `x64-Debug`

1. You have rebuilt all projects

**Comment by raypenper** [comment]
@mizuno-gsinet YES!YES! it hits the breakpoint. Have it caculated the empirical variogram from the testing data? What should i do next? 

![image](https://user-images.githubusercontent.com/41855946/53460980-fc4efe80-3a79-11e9-89e0-ff5b2b2b37db.png)

**Comment by mizuno-gsinet** [comment]
@raypenper 

>Have it caculated the empirical variogram from the testing data?

No. Why don't you read the message?

**Comment by raypenper** [comment]
@mizuno-gsinet Sorry. but i don't know how to set bin width.-_-

**Comment by mizuno-gsinet** [comment]
@raypenper Just append it to command-line arguments:

```
      "args": [
        "--in filename --bin-width 10 ..."
      ]
```

**Comment by raypenper** [comment]
@mizuno-gsinet Oh. i see, i need to set parameter in command-line. Thanks again.

**Comment by raypenper** [comment]
@mizuno-gsinet i have to ask for your help again. Is there something wrong with my data? The value type is double, it seems well.

![image](https://user-images.githubusercontent.com/41855946/53472650-2f59b800-3aa3-11e9-86cb-e18a60e986ac.png)

**Comment by mizuno-gsinet** [comment]
@raypenper I'm not sure. Could you send me <mizuno(at)gsinet.co.jp> the original data if you don't mind sharing it?

**Comment by raypenper** [comment]
@mizuno-gsinet Sure, it would be so nice for you to help me checking the data, but do you have an e-mail ? i can't find a way to send my data to you via <mizuno(at)gsinet.co.jp>

**Comment by mizuno-gsinet** [comment]
@raypenper That is my e-mail address, modified a little to protect it from spam.

**Comment by raypenper** [comment]
@mizuno-gsinet OK, copy that.

**Comment by mizuno-gsinet** [comment]
@raypenper Thank you, I've just received your data. Could you try removing trailing spaces on each line?

**Comment by raypenper** [comment]
@mizuno-gsinet thanks for your advice. It really took a long time to caculate the empirical variogram. i believe the next step is to fit the variogram curves. Should i use variogram fit model directly?
![image](https://user-images.githubusercontent.com/41855946/53477194-24a52000-3aaf-11e9-93ec-2ccca9c7a5f6.png)

**Comment by mizuno-gsinet** [comment]
>It really took a long time to caculate the empirical variogram.

You should try the Release build. 

>Should i use variogram fit model directly?

What do you mean by that? BTW, I think you should pass a larger value to `--n-bins`.

**Comment by raypenper** [comment]
> You should try the Release build.
Yes. i think i render the value of bins too small, but a small bin size will get a better performace than a large one, right?
> What do you mean by that? 
It means that i don't know clearly what to do next after we got the empirical variogram.

**Comment by raypenper** [comment]
> You should try the Release build.

Yes. i think i rendered the value of bins too small, but a small bin size will get a better performace than a larger one, right?

> What do you mean by that?

It means that i don't know clearly what to do next after we got the empirical variogram.

**Comment by mizuno-gsinet** [comment]
>a small bin size will get a better performace than a larger one, right?

Not really. Neither `--bin-width` nor `n-bins` affects performance. Empirical variogram computation [requires O(Npoints^2) iterations](https://github.com/polatory/polatory/blob/cca97e85afaabf19fc01ac6d470dc3137b3710d6/src/kriging/empirical_variogram.cpp#L30-L45).

**Comment by raypenper** [comment]
@mizuno-gsinet Yes, i agree with you, computing emprical variogram requires every two other porints.

Can you please tell me how to use the other two models(kriging-fit and kriging predict)?

**Comment by mizuno-gsinet** [comment]
@raypenper What have you tried so far? Have you read the usage message?

**Comment by raypenper** [comment]
@mizuno-gsinet Sorry, i should'n have asked in that way, i need to find the emprical variogram file and render it to the fitting model.

**Comment by mizuno-gsinet** [comment]
@raypenper You can copy the console output.

**Comment by raypenper** [comment]
@mizuno-gsinet Thanks, i will, but now i can't find where the output file of emprical variogram is.
should i copy the output in the console window and creat a new file for fitting model?
![image](https://user-images.githubusercontent.com/41855946/53541042-f9740c80-3b52-11e9-9dcb-4604b8fb6c46.png)

![image](https://user-images.githubusercontent.com/41855946/53542049-a05aa780-3b57-11e9-9914-3c8581005a7c.png)

**Comment by mizuno-gsinet** [comment]
@raypenper I think `variogram.txt...` is not a valid filename on Windows.

**Comment by raypenper** [comment]
@mizuno-gsinet Oh God, how careless i am. but after i revised the output path. it still got nothing.
and i send you another geological data. Please help me checking it.

![image](https://user-images.githubusercontent.com/41855946/53552503-66e56480-3b76-11e9-8c08-46306af9a2f8.png)

**Comment by mizuno-gsinet** [comment]
@raypenper Please replace multiple spaces with a single space or comma. The parser is not flexible.

**Comment by raypenper** [comment]
@mizuno-gsinet Yes, the problem has fixed, but the predict model requires mesh-bbox. What is the format of its property(xmin ymin zmin xmax ymax zmax)?

![image](https://user-images.githubusercontent.com/41855946/53561302-702bfc80-3b89-11e9-8723-1aece98f7efd.png)

**Comment by mizuno-gsinet** [comment]
@raypenper Wait... aren’t the psill and range too large?

**Comment by raypenper** [comment]
@mizuno-gsinet yes. i think so, but it reads CONVERGENCE. i don't know why.
i sent you another data yesterday. Can you help me checking the data?

**Comment by mizuno-gsinet** [comment]
@raypenper I'm sorry but I don't have much time. Try several different initial parameters and always plot the empirical and model variograms together. You can see the definition of covariance function `cov_quasi_spherical9` [here](https://github.com/polatory/polatory/blob/cca97e85afaabf19fc01ac6d470dc3137b3710d6/include/polatory/rbf/cov_quasi_spherical9.hpp#L21-L28).

And please learn how to run command-line programs in cmd.exe. That should be easier than running in VS unless you want to debug them.

**Comment by raypenper** [comment]
@mizuno-gsinet Thank you, i am using cmd.exe to run the program, it's really faster now.

**Comment by mizuno-gsinet** [comment]
@raypenper Apparently, the initial values are not appropriate. Have you plotted the empirical variogram? The sill should be set to the variance of your data.

**Comment by raypenper** [comment]
@mizuno-gsinet wait, need i plot the empirical variogram to get the sill?i thought the kriging_fit model can do this. 

This is the outcome of empirical variogram:
![image](https://user-images.githubusercontent.com/41855946/53625001-ea698900-3c3c-11e9-9532-162f21ebd400.png)

and this is the file created from kriging_variogram model:
![image](https://user-images.githubusercontent.com/41855946/53625291-a925a900-3c3d-11e9-90d6-5385701e4a7b.png)

**Comment by mizuno-gsinet** [comment]
Sorry, but I’m not going to give you a lecture on kriging.

**Comment by raypenper** [comment]
@mizuno-gsinet I am sorry to have so many questions, but you honestly don't need to talk about theory of kriging. I reviewed it again, studied through the code and i almost got the output but here is one last question. how to set mesh-bbox size?

![image](https://user-images.githubusercontent.com/41855946/53679977-66340600-3d0f-11e9-9ceb-7bc1186e0b1f.png)

**Comment by mizuno-gsinet** [comment]
@raypenper The format of the command line is ok. However,

1. If you're doing ordinary kriging, you don't need to specify the `--dim` option. Additionary, 4 is not a valid value for that option.

2. A reasonable value of `--bbox` is (a subset of) the bounding box of the data points as you normally don't want extrapolation.

**Comment by raypenper** [comment]
@mizuno-gsinet Sorry. i tried so many values(both the bounding box and a subset) of --bbox. but it still reads "rank cannot be larger than size".

![image](https://user-images.githubusercontent.com/41855946/53707245-25500480-3e69-11e9-9ca4-d5f16b3e6d7a.png)

the bounding box of data is (621553.67 5748274.15 -5285.68 631914.09 5751454.27 -3088.28)
![image](https://user-images.githubusercontent.com/41855946/53707589-8cba8400-3e6a-11e9-917a-faa58409b0d8.png)

**Comment by mizuno-gsinet** [comment]
@raypenper I found a memory-management bug in `polatory::interpolant::fit()`. Let me fix it and inform you when it is done.

**Comment by mizuno-gsinet** [comment]
@raypenper I fixed the bug in `master` branch and tested kriging_prediction program with your data. I recommend you start with `--tol 0.1` and `--mesh-res 20` which still give a pretty fine interpolation.

**Comment by raypenper** [comment]
@mizuno-gsinet Gratefully thank you, i pulled the latest master branch and rebuilded the project, the value of psill and range get by kriging_fit have changed. But when i use kriging_prediction, it still got the same error.

![image](https://user-images.githubusercontent.com/41855946/53721557-762e2000-3e9e-11e9-9b97-2b62e4711ea8.png)

BTW, what's the format of mesh-bbox in launch.vs.json? 
![image](https://user-images.githubusercontent.com/41855946/53721799-0f5d3680-3e9f-11e9-9eb8-6b8288dd46d8.png)

**Comment by mizuno-gsinet** [comment]
>the value of psill and range get by kriging_fit have changed.

I've done nothing to kriging_fit. If that's the case, maybe the solver is not deterministic.

>But when i use kriging_prediction, it still got the same error.

That's strange. Here are the command-line and output in my environment.

```cmd
kriging_predict.exe --in "D:\path\to\data.txt" --psill 645249 --range 3900 --mesh-bbox 621553.67 5748274.15 -5285.68 631914.09 5751454.27 -3088.28 --mesh-res 20 --mesh-isoval -5000 --tol 0.1 --mesh-out "D:\path\to\output.obj"
```

![image](https://user-images.githubusercontent.com/29035331/53772488-dddd7d00-3f29-11e9-8e82-8cf309bc72b4.png)

Could you try cloning and building the project again?

**Comment by mizuno-gsinet** [comment]
@raypenper Beware that the build directory is not `build` but `build\x64-Debug` or `build\x64-Release` if you are building with Visual Studio.

**Comment by raypenper** [comment]
@mizuno-gsinet なるほど! Finally! it worked. i am so grateful for your help. Thanks again.
