### ISSUE TITLE
Improve fine-level preconditioner.

### ISSUE THREAD

**Issue by mizuno-gsinet** [polatory/polatory#5]
Currently, `preconditioner::fine_grid` fits RBF interpolant WITHOUT polynomials to the subset of points. Such an interpolation system is generally not SPD and ill-conditioned.

The improved fine-level preconditioner should work as follows:

### Input

- Lagrange basis.
- Set of points from which the Lagrange basis is constructed (L).
- Set of points (P) at the level which includes L.

### Setup

1. Construct subdomains. Each subdomain consists of:
    <dl>
        <dt>Solution points (S)</dt>
        <dd>L ∩ the points where corresponding components of γ are solved for.</dd>
        <dt>Inner points (I)</dt>
        <dd>The points where corresponding components of global λ will be updated.</dd>
    </dl>
1. For each subdomain,
    1. Construct the principal submatrix of A with the indices of S.
    1. Construct and factorize the principal submatrix of Q^T A Q with the indices of S \ L.
    1. Construct the submatrix of -E with columns at the indices of S \ L.

### Process per Iteration

1. For each subdomain,
    1. Approximately solve SPD system Q^T A Q γ = Q^T d for γ at S, set the rest of γ to 0.
    1. Compute λ = Q γ.
    1. Update components of the global λ correspond to I.
1. Orthogonalize global λ to the polynomial space.

![texclip20171017130948](https://user-images.githubusercontent.com/29035331/31646358-7a5372dc-b33c-11e7-8c49-0d9e64836e44.png)

![texclip20171017125601](https://user-images.githubusercontent.com/29035331/31646072-90f869b8-b33a-11e7-8019-172543a679a3.png)

![texclip20171017112250](https://user-images.githubusercontent.com/29035331/31643795-8e0aca28-b32d-11e7-9684-28b0c6d71486.png)

![texclip20171017112222](https://user-images.githubusercontent.com/29035331/31643773-77a0b3e2-b32d-11e7-9bba-f1806dd5d14a.png)

**Comment by CloudComputer** [comment]
The preconditioner and the formulas  is quite  difficult to understand for me. Is there some reference or documentation to make it easier to understand?

**Comment by mizuno-gsinet** [comment]
@CloudComputer The details of the preconditioner is described in the paper: https://doi.org/10.1137/S1064827599361771

Names of vectors and matrices in `coarse_grid` and `fine_grid` are taken from the paper, so please take a look at it.

**Comment by CloudComputer** [comment]
@mizuno-gsinet Is your implementation an extension of the two-level method? Is there a paper about the extension?

**Comment by mizuno-gsinet** [comment]
@CloudComputer 

>Is your implementation an extension of the two-level method?

Basically, yes. However, its configuration is based on trial-and-error. So there is no theoretical basis behind it.

**Comment by CloudComputer** [comment]
@mizuno-gsinet Many thanks for the prompt reply.
