### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by mbahri** [polatory/polatory#81]
Hi

This is just to let you know that on Ubuntu 19.04 (in a docker container) I had to add the package `double-conversion` to the list of dependencies installed with vcpkg:
```
./vcpkg install abseil boost-filesystem boost-program-options boost-serialization ceres double-conversion eigen3 flann gsl-lite gtest double-conversion --triplet x64-linux
```

Best

**Comment by mizuno-gsinet** [comment]
Hello, I've just added dependency on double-conversion in 25370138931424ddff722bbc53fb15924be35b85. I'm sorry there is no announcement about that.
